export const faq = [
  {
    title: 'What I will get?',
    description:
      'A set of 6 AI baby generated photos, 3 for boy and 3 for girl + a free gift (story) to share on social media.',
  },
  {
    title: 'Can I give you only 1 photo?',
    description:
      'Of course, feel free to upload it in Single snapshot on the checkout page.',
  },
  {
    title: 'What about privacy?',
    description:
      'Privacy is our top priority for our customers, your email will be used only to send you the delivery, we don’t sell your data, and we won’t send you any promotional emails.',
  },
  {
    title: 'How my photos will be used?',
    description:
      'They will be used to train our models, generate the baby photos, and then remove them immediately from our servers.',
  },
  {
    title: 'Where my data is stored?',
    description:
      'Name & email on our own platform, and the baby photos will be generated by our 3rd party patner which we have a private and secure access with, no one else can access your photos.',
  },
  {
    title: 'Is the payment secure?',
    description:
      'Yes, we use Stripe to process payments, and we don’t store any credit/debit card data.',
  },
  {
    title: 'What about refunds?',
    description:
      'The order will be canceled if the provided photos didn’t meet the requirements, and after we reached out we didn’t receive an update from you within 3 days, in this case, the funds will be returned to the source. Also we offer up to 2 free revisions after the delivery.',
  },
]
